import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { MovieTile, SearchInput } from "#components";
import useFetchMovies from "src/hooks/useFetchMovies";
import useFilters from "src/hooks/useFilters";

const Home: NextPage = () => {
  const { filters, setFilterValue, updatePage } = useFilters();
  const { performFetch, movies, isLoading, meta } = useFetchMovies();

  const handleOnClickShowMore = () => console.log("handleOnClickShowMore");

  useEffect(() => {
    filters.s && performFetch(filters);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filters]);

  console.log("MOVIES", isLoading, movies, meta);
  return (
    <>
      <Head>
        <title>Welcome to WDIW</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SearchInput
          name="s"
          placeholder="What movie/serie you just watched?"
          onChange={(name, value) => setFilterValue(name, value)}
          debounceOnChangeDelay={500}
        />

        <div>
          {movies.map(movie => (
            <MovieTile key={movie.imdbID} movie={movie} onClick={() => {}} />
          ))}
        </div>

        {isLoading && <p>Loading...</p>}

        {meta && movies.length < meta.totalResults && (
          <button type="button" onClick={() => updatePage(filters.page + 1)}>
            Show More
          </button>
        )}
      </main>
    </>
  );
};

export default Home;
